"""empty message

Revision ID: 295c08001281
Revises: b5321cbb172d
Create Date: 2022-12-22 19:02:38.859334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295c08001281'
down_revision = 'b5321cbb172d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
