"""empty message

Revision ID: 69df88ee8c03
Revises: 6a267d5916c2
Create Date: 2022-12-22 18:41:52.738709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69df88ee8c03'
down_revision = '6a267d5916c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_column('proof')

    # ### end Alembic commands ###
