"""empty message

Revision ID: 6a267d5916c2
Revises: bb82912c675a
Create Date: 2022-12-22 18:36:12.396493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a267d5916c2'
down_revision = 'bb82912c675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_column('previous_proof')
        batch_op.drop_column('proof')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('previous_proof', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
