"""empty message

Revision ID: a8bfa4ce393f
Revises: cf6efea37f46
Create Date: 2022-12-22 17:57:13.517456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bfa4ce393f'
down_revision = 'cf6efea37f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('hash', sa.String(length=256), nullable=False),
    sa.Column('proof', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=256), nullable=False),
    sa.Column('previous_proof', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block')
    # ### end Alembic commands ###
