"""empty message

Revision ID: bb82912c675a
Revises: b64930c9b326
Create Date: 2022-12-22 18:28:23.413665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb82912c675a'
down_revision = 'b64930c9b326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
